// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageStandby.Backend.Data;

#nullable disable

namespace StorageStandby.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004042707_AutomaticSyncInterval")]
    partial class AutomaticSyncInterval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StorageStandby.Backend.Models.CloudToken", b =>
                {
                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Provider", "AccountId");

                    b.ToTable("CloudTokens");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.PendingSyncItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Changed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Moved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Renamed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WatchedFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PendingSyncQueue");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SyncEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncedItemIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncedItems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SystemSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnfinishedItemIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnfinishedItems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("WatchedFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemSettingsId");

                    b.ToTable("SyncEvents");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomaticSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticSyncs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseSyncUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutomaticSyncIntervalMinutes = 60,
                            AutomaticSyncs = true,
                            IsSyncPaused = false
                        });
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("IgnoreRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Problem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrackSnapshots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WatchedFolders");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderCloudMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteFolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StoreZip")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WatchedFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WatchedFolderId");

                    b.ToTable("WatchedFolderCloudMetadata");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SyncEvent", b =>
                {
                    b.HasOne("StorageStandby.Backend.Models.SystemSettings", null)
                        .WithMany("SyncEvents")
                        .HasForeignKey("SystemSettingsId");

                    b.OwnsMany("StorageStandby.Backend.Models.FailedItemsDetails", "FailedItems", b1 =>
                        {
                            b1.Property<long>("SyncEventId")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FailedItem")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("SyncEventId", "Id");

                            b1.ToTable("FailedItemsDetails");

                            b1.WithOwner()
                                .HasForeignKey("SyncEventId");
                        });

                    b.Navigation("FailedItems");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderCloudMetadata", b =>
                {
                    b.HasOne("StorageStandby.Backend.Models.WatchedFolder", null)
                        .WithMany("AssignedClouds")
                        .HasForeignKey("WatchedFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SystemSettings", b =>
                {
                    b.Navigation("SyncEvents");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolder", b =>
                {
                    b.Navigation("AssignedClouds");
                });
#pragma warning restore 612, 618
        }
    }
}
