// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageStandby.Backend.Data;

#nullable disable

namespace StorageStandby.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823024841_WatchedFolderSystemSettings")]
    partial class WatchedFolderSystemSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StorageStandby.Backend.Models.CloudToken", b =>
                {
                    b.Property<int>("ProviderName")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProviderName", "AccountId");

                    b.ToTable("CloudTokens");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SyncEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SystemSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemSettingsId");

                    b.ToTable("SyncEvent");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("BackupIgnoreProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LargeFolderThresholdBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseSyncUntil")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredProvider")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackupIgnoreProfile = "[\"*.tmp\",\"node_modules/\"]",
                            LargeFolderThresholdBytes = 1073741824L
                        });
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SyncEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SyncEventId");

                    b.ToTable("WatchedChild");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderCloudMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WatchedFolderParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WatchedFolderParentId");

                    b.ToTable("WatchedFolderCloudMetadata");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsZipCompressionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PathsBlacklist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WatchedFolders");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SyncEvent", b =>
                {
                    b.HasOne("StorageStandby.Backend.Models.SystemSettings", null)
                        .WithMany("SyncEvents")
                        .HasForeignKey("SystemSettingsId");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedChild", b =>
                {
                    b.HasOne("StorageStandby.Backend.Models.WatchedFolderParent", "Parent")
                        .WithMany("WatchedChildren")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorageStandby.Backend.Models.SyncEvent", null)
                        .WithMany("SyncedItems")
                        .HasForeignKey("SyncEventId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderCloudMetadata", b =>
                {
                    b.HasOne("StorageStandby.Backend.Models.WatchedFolderParent", null)
                        .WithMany("AssignedClouds")
                        .HasForeignKey("WatchedFolderParentId");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SyncEvent", b =>
                {
                    b.Navigation("SyncedItems");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SystemSettings", b =>
                {
                    b.Navigation("SyncEvents");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderParent", b =>
                {
                    b.Navigation("AssignedClouds");

                    b.Navigation("WatchedChildren");
                });
#pragma warning restore 612, 618
        }
    }
}
