// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageStandby.Backend.Data;

#nullable disable

namespace StorageStandby.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830201507_WatchedFolderFileSyncRecords")]
    partial class WatchedFolderFileSyncRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StorageStandby.Backend.Models.CloudToken", b =>
                {
                    b.Property<int>("ProviderName")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProviderName", "AccountId");

                    b.ToTable("CloudTokens");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SyncEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncedItems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SystemSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WatchedFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemSettingsId");

                    b.ToTable("SyncEvent");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalIgnoreRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GlobalPreferredProvider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseSyncUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GlobalIgnoreRules = "*.tmp;node_modules/"
                        });
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("IgnoreRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsZipCompressionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepSnapshotsInSameAccount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredProvider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Problem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackSnapshots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WatchedFolders");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderCloudMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteFolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("WatchedFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WatchedFolderId");

                    b.ToTable("WatchedFolderCloudMetadata");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SyncEvent", b =>
                {
                    b.HasOne("StorageStandby.Backend.Models.SystemSettings", null)
                        .WithMany("SyncEvents")
                        .HasForeignKey("SystemSettingsId");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolderCloudMetadata", b =>
                {
                    b.HasOne("StorageStandby.Backend.Models.WatchedFolder", "WatchedFolder")
                        .WithMany("AssignedClouds")
                        .HasForeignKey("WatchedFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchedFolder");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.SystemSettings", b =>
                {
                    b.Navigation("SyncEvents");
                });

            modelBuilder.Entity("StorageStandby.Backend.Models.WatchedFolder", b =>
                {
                    b.Navigation("AssignedClouds");
                });
#pragma warning restore 612, 618
        }
    }
}
